# send a chat message
POST http://localhost:11434/api/generate
Content-Type: application/json
Connection: keep-alive

{
  "model": "ds-v2:latest",
  "stream": false,
  "prompt": "What is your model name and version ?"
}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
date: Tue, 28 Jul 2026 11:26:12 GMT
content-length: 1028
###
# list all models
GET http://localhost:11434/api/tags

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
date: Wed, 29 Jul 2026 13:16:12 GMT
connection: close
transfer-encoding: chunked
###
# list running models
GET http://localhost:11434/api/ps

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
date: Tue, 28 Jul 2026 09:29:51 GMT
content-length: 13
connection: close
###
# Bad request
POST http://localhost:11434/api/generate
Content-Type: application/json

{
    "fakeRequest": null
}

HTTP/1.1 404  - Not Found
content-type: application/json; charset=utf-8
date: Tue, 28 Jul 2026 09:29:54 GMT
content-length: 30
connection: close